name: Notificar a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d " Nuevo push al repositorio en la rama main" ntfy.sh/devops-itla
